// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjauflmbpyrfxgbwsayn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqYXVmbG1icHlyZnhnYndzYXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzE3ODIsImV4cCI6MjA2OTYwNzc4Mn0.FZHuVEVZ2xsSAenXzUCEBILw-4L6PcliW5PzmHV6_T4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});